// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonModal: typeof import('./components/CommonModal.vue')['default']
    CommonSelectInput: typeof import('./components/CommonSelectInput.vue')['default']
    DisplayMember: typeof import('./components/DisplayMember.vue')['default']
    FavoriteSearch: typeof import('./components/FavoriteSearch.vue')['default']
    GenderInput: typeof import('./components/GenderInput.vue')['default']
    PipiFamily: typeof import('./views/PipiFamily.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    TestRedEnvelope: typeof import('./views/TestRedEnvelope.vue')['default']
  }
}
